# Generated by Django 5.2.11 on 2026-03-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_label', models.CharField(max_length=200)),
                ('field_type', models.CharField(choices=[('text', 'Short Text'), ('textarea', 'Long Text'), ('number', 'Number'), ('dropdown', 'Dropdown Select'), ('multi_select', 'Multi-Select'), ('radio', 'Radio Buttons'), ('file', 'File Upload'), ('date', 'Date Picker'), ('url', 'URL Input')], max_length=20)),
                ('field_options', models.JSONField(blank=True, default=list, help_text='Options for dropdown/multi-select/radio')),
                ('is_required', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('placeholder', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('description', models.TextField(help_text='Rich text description of the event')),
                ('category', models.CharField(choices=[('hackathon', 'Hackathon'), ('coding_contest', 'Coding Contest'), ('workshop', 'Workshop'), ('quiz', 'Quiz / Competition'), ('paper_presentation', 'Paper Presentation'), ('design', 'Design Challenge'), ('ideathon', 'Ideathon'), ('case_study', 'Case Study'), ('cultural', 'Cultural'), ('sports', 'Sports'), ('other', 'Other')], max_length=30)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='events/banners/')),
                ('mode', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('hybrid', 'Hybrid')], max_length=10)),
                ('venue', models.CharField(blank=True, default='', max_length=300)),
                ('platform_link', models.URLField(blank=True, default='', max_length=500)),
                ('registration_start', models.DateTimeField()),
                ('registration_end', models.DateTimeField()),
                ('event_start', models.DateTimeField()),
                ('event_end', models.DateTimeField()),
                ('submission_deadline', models.DateTimeField(blank=True, null=True)),
                ('participation_type', models.CharField(choices=[('individual', 'Individual'), ('team', 'Team-Based'), ('both', 'Both')], default='individual', max_length=15)),
                ('min_team_size', models.PositiveIntegerField(blank=True, null=True)),
                ('max_team_size', models.PositiveIntegerField(blank=True, null=True)),
                ('allow_team_creation', models.BooleanField(default=True)),
                ('allow_join_requests', models.BooleanField(default=True)),
                ('eligibility', models.TextField(blank=True, default='')),
                ('prize_pool_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('has_participation_certificate', models.BooleanField(default=False)),
                ('has_merit_certificate', models.BooleanField(default=False)),
                ('max_participants', models.PositiveIntegerField(blank=True, null=True)),
                ('registration_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=255)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=15)),
                ('rules', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=15)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='EventJudge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(blank=True, default='', max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='events/judges/')),
                ('bio', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='EventPrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=50)),
                ('prize_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('prize_description', models.CharField(blank=True, default='', max_length=500)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EventRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField()),
                ('round_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('elimination_criteria', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['round_number'],
            },
        ),
        migrations.CreateModel(
            name='EventSponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='events/sponsors/')),
                ('website_url', models.URLField(blank=True, default='', max_length=500)),
                ('sponsor_type', models.CharField(choices=[('title', 'Title Sponsor'), ('gold', 'Gold Sponsor'), ('silver', 'Silver Sponsor'), ('bronze', 'Bronze Sponsor'), ('partner', 'Partner')], default='partner', max_length=10)),
            ],
            options={
                'ordering': ['sponsor_type'],
            },
        ),
    ]
