# Generated by Django 5.2.11 on 2026-03-02 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customformfield',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='events.event'),
        ),
        migrations.AddField(
            model_name='eventannouncement',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='events.event'),
        ),
        migrations.AddField(
            model_name='eventfaq',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='events.event'),
        ),
        migrations.AddField(
            model_name='eventjudge',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judges', to='events.event'),
        ),
        migrations.AddField(
            model_name='eventprize',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='events.event'),
        ),
        migrations.AddField(
            model_name='eventround',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='events.event'),
        ),
        migrations.AddField(
            model_name='eventsponsor',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsors', to='events.event'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['status', 'category'], name='events_even_status_22259e_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['registration_end'], name='events_even_registr_e046a1_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['is_featured'], name='events_even_is_feat_765082_idx'),
        ),
    ]
