# Generated by Django 6.0.3 on 2026-03-28 05:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0002_event_is_featured_eventannouncement_eventjudge_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EventCreationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("hackathon", "Hackathon"),
                            ("workshop", "Workshop"),
                            ("coding_contest", "Coding Contest"),
                            ("quiz", "Quiz / Competition"),
                            ("paper_presentation", "Paper Presentation"),
                            ("design_challenge", "Design Challenge"),
                            ("ideathon", "Ideathon"),
                            ("case_study", "Case Study"),
                            ("cultural", "Cultural"),
                            ("sports", "Sports"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("offline", "Offline"),
                            ("hybrid", "Hybrid"),
                        ],
                        default="offline",
                        max_length=10,
                    ),
                ),
                (
                    "participation_type",
                    models.CharField(
                        choices=[
                            ("individual", "Individual"),
                            ("team", "Team"),
                            ("both", "Both"),
                        ],
                        default="individual",
                        max_length=12,
                    ),
                ),
                ("registration_start", models.DateTimeField()),
                ("registration_end", models.DateTimeField()),
                ("event_start", models.DateTimeField()),
                ("event_end", models.DateTimeField()),
                ("venue", models.CharField(blank=True, default="", max_length=300)),
                ("platform_link", models.URLField(blank=True, default="")),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        default=100,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("min_team_size", models.PositiveSmallIntegerField(default=1)),
                ("max_team_size", models.PositiveSmallIntegerField(default=1)),
                (
                    "registration_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("rules", models.TextField(blank=True, default="")),
                ("contact_info", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("review_note", models.TextField(blank=True, default="")),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_event",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="creation_request",
                        to="events.event",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_creation_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_event_creation_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["status", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="idx_event_request_status_time",
                    ),
                    models.Index(
                        fields=["requested_by", "-created_at"],
                        name="idx_event_request_user_time",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("registration_end__gte", models.F("registration_start"))
                        ),
                        name="chk_event_request_reg_dates",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("event_end__gte", models.F("event_start"))),
                        name="chk_event_request_event_dates",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("max_team_size__gte", models.F("min_team_size"))
                        ),
                        name="chk_event_request_team_size",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("capacity__gte", 1)),
                        name="chk_event_request_capacity_positive",
                    ),
                ],
            },
        ),
    ]
