# Generated by Django 6.0.2 on 2026-03-04 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(blank=True, default="", max_length=20)),
                ("college", models.CharField(blank=True, default="", max_length=200)),
                ("branch", models.CharField(blank=True, default="", max_length=100)),
                ("year", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("bio", models.TextField(blank=True, default="", max_length=500)),
                ("github", models.URLField(blank=True, default="")),
                ("linkedin", models.URLField(blank=True, default="")),
                (
                    "skills",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Comma-separated list of skills",
                        max_length=500,
                    ),
                ),
                ("email_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
    ]
