# Generated by Django 6.0.3 on 2026-03-09 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0003_add_custom_form_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrationresponse",
            name="file_url",
            field=models.FileField(
                blank=True,
                help_text="Uploaded file for file-type custom fields",
                upload_to="registrations/uploads/",
            ),
        ),
        migrations.AlterField(
            model_name="customformfield",
            name="field_label",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="customformfield",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("text", "Short Text"),
                    ("textarea", "Long Text"),
                    ("number", "Number"),
                    ("dropdown", "Dropdown"),
                    ("multi_select", "Multi-Select"),
                    ("radio", "Radio Buttons"),
                    ("file", "File Upload"),
                    ("date", "Date"),
                    ("url", "URL"),
                ],
                default="text",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="customformfield",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="registrationresponse",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.CreateModel(
            name="RegistrationTechStack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tech_name", models.CharField(max_length=50)),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tech_stacks",
                        to="registration.registration",
                    ),
                ),
            ],
            options={
                "ordering": ["registration", "-is_primary", "tech_name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("registration", "tech_name"), name="uniq_reg_tech"
                    )
                ],
            },
        ),
    ]
