# Generated by Django 5.2.11 on 2026-03-02 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_value', models.TextField(blank=True, default='')),
                ('file_url', models.FileField(blank=True, null=True, upload_to='registrations/uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationTechStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech_name', models.CharField(max_length=50)),
                ('is_primary', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-is_primary', 'tech_name'],
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_type', models.CharField(choices=[('individual', 'Individual'), ('team', 'Team')], max_length=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='confirmed', max_length=15)),
                ('registration_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('looking_for_team', models.BooleanField(default=False)),
                ('preferred_role', models.CharField(blank=True, choices=[('frontend_dev', 'Frontend Developer'), ('backend_dev', 'Backend Developer'), ('fullstack_dev', 'Full Stack Developer'), ('mobile_dev', 'Mobile Developer'), ('ui_ux', 'UI/UX Designer'), ('ml_ai', 'ML/AI Engineer'), ('data_scientist', 'Data Scientist'), ('devops', 'DevOps Engineer'), ('project_manager', 'Project Manager'), ('other', 'Other')], default='', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
