# Generated by Django 6.0.3 on 2026-03-15 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0002_event_is_featured_eventannouncement_eventjudge_and_more"),
        ("team", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Submission",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "project_url",
                    models.URLField(
                        blank=True, default="", help_text="GitHub / live demo URL"
                    ),
                ),
                (
                    "presentation_url",
                    models.URLField(
                        blank=True, default="", help_text="Slides / Figma link"
                    ),
                ),
                (
                    "file_upload",
                    models.FileField(blank=True, upload_to="submissions/files/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("reviewed", "Reviewed"),
                            ("disqualified", "Disqualified"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=15,
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("judge_notes", models.TextField(blank=True, default="")),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="events.event",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="team.team",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["event", "status"], name="idx_submission_event_status"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("team__isnull", False)),
                        fields=("event", "team"),
                        name="uniq_submission_team_event",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("team__isnull", True)),
                        fields=("event", "user"),
                        name="uniq_submission_user_event",
                    ),
                ],
            },
        ),
    ]
