# Generated by Django 6.0.2 on 2026-03-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="looking_for",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Roles or skills the team is looking for",
                max_length=500,
            ),
        ),
    ]
