# Generated by Django 6.0.2 on 2026-03-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0002_team_looking_for"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Short description of what the team is building",
                max_length=1500,
            ),
        ),
    ]
