# Generated by Django 5.2.11 on 2026-03-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('join_request', 'Join Request'), ('request_approved', 'Request Approved'), ('request_declined', 'Request Declined'), ('new_message', 'New Message'), ('announcement', 'Announcement'), ('registration', 'Registration'), ('reminder', 'Event Reminder')], max_length=20)),
                ('reference_id', models.PositiveIntegerField(blank=True, null=True)),
                ('reference_type', models.CharField(blank=True, default='', max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
