# Generated by Django 6.0.3 on 2026-03-15 04:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0002_event_is_featured_eventannouncement_eventjudge_and_more"),
        ("registration", "0004_registrationresponse_file_url_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "cert_type",
                    models.CharField(
                        choices=[
                            ("participation", "Participation"),
                            ("merit", "Merit"),
                            ("winner", "Winner"),
                        ],
                        default="participation",
                        max_length=20,
                    ),
                ),
                (
                    "verification_token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "pdf_file",
                    models.FileField(blank=True, upload_to="certificates/pdfs/"),
                ),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to="events.event",
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to="registration.registration",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-issued_at"],
                "indexes": [
                    models.Index(fields=["user", "-issued_at"], name="idx_cert_user"),
                    models.Index(fields=["verification_token"], name="idx_cert_token"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("registration", "cert_type"),
                        name="uniq_cert_per_registration_type",
                    )
                ],
            },
        ),
    ]
